FROM debian:bookworm-slim AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y curl cron unzip && rm -rf /var/lib/apt/lists/*
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip

RUN mkdir /storage
COPY upload.sh ./
RUN chmod +x upload.sh

ENTRYPOINT ["/app/upload.sh"]
